services:
  webui:
    build: .
    image: javimosch/updateable-node
    volumes:
      - .:/app
    ports:
      - "3888:3888"
      - "3089:3000"
    env_file:
      - .env
    command: ["npm", "run", "dev"]
